// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SureBudgetRequest.Infrastructure.Persistence;

#nullable disable

namespace SureBudgetRequest.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530080853_AddNoteToBudgetRequestModification")]
    partial class AddNoteToBudgetRequestModification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.AdvanceUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<Guid>("BudgetRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_request_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<DateTime>("SpentOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spent_on");

                    b.HasKey("Id")
                        .HasName("pk_advance_usages");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_advance_usages_attachment_id");

                    b.HasIndex("BudgetRequestId")
                        .HasDatabaseName("ix_advance_usages_budget_request_id");

                    b.ToTable("advance_usages", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.ApprovalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actioned_at");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_id");

                    b.Property<Guid>("BudgetRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_request_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.HasKey("Id")
                        .HasName("pk_approval_actions");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("ix_approval_actions_approver_id");

                    b.HasIndex("BudgetRequestId")
                        .HasDatabaseName("ix_approval_actions_budget_request_id");

                    b.ToTable("approval_actions", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_request_id");

                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("category");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("stored_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("BudgetRequestId")
                        .HasDatabaseName("ix_attachments_budget_request_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.BudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_budget_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_categories_name");

                    b.ToTable("budget_categories", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.BudgetRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsPartialPayment")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_partial_payment");

                    b.Property<decimal>("ApprovedAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("approved_amount");

                    b.Property<Guid?>("BudgetCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_category_id");

                    b.Property<Guid?>("CoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("coa_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("DepartmentIdAtSubmission")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id_at_submission");

                    b.Property<decimal>("DepartmentLimitAtSubmission")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("department_limit_at_submission");

                    b.Property<Guid>("DeptHeadIdAtSubmission")
                        .HasColumnType("uuid")
                        .HasColumnName("dept_head_id_at_submission");

                    b.Property<string>("DeptHeadNameAtSubmission")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dept_head_name_at_submission");

                    b.Property<decimal>("ExchangeRateAtSubmission")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("exchange_rate_at_submission");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<decimal?>("ManualExchangeRate")
                        .HasColumnType("numeric")
                        .HasColumnName("manual_exchange_rate");

                    b.Property<decimal?>("MonthlyLimitAtSubmission")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_limit_at_submission");

                    b.Property<string>("MonthlyOverrunJustification")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("monthly_overrun_justification");

                    b.Property<decimal?>("MonthlySpendBeforeAtSubmission")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_spend_before_at_submission");

                    b.Property<string>("PartialPaymentDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("partial_payment_detail");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reasons");

                    b.Property<DateTime?>("ReconciliationDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reconciliation_deadline");

                    b.Property<DateTime?>("ReconciliationSubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reconciliation_submitted_at");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("refund_amount");

                    b.Property<DateTime?>("RefundReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refund_received_at");

                    b.Property<Guid?>("RefundReceivedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_received_by_user_id");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_date");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("requested_amount");

                    b.Property<decimal>("RequestedAmountInMmkAtSubmission")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("requested_amount_in_mmk_at_submission");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("RequesterNameAtSubmission")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requester_name_at_submission");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid?>("WithdrawMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("withdraw_method_id");

                    b.Property<string>("WithdrawerJobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("withdrawer_job_title");

                    b.Property<string>("WithdrawerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("withdrawer_name");

                    b.HasKey("Id")
                        .HasName("pk_budget_requests");

                    b.HasIndex("BudgetCategoryId")
                        .HasDatabaseName("ix_budget_requests_budget_category_id");

                    b.HasIndex("CoaId")
                        .HasDatabaseName("ix_budget_requests_coa_id");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_budget_requests_currency_code");

                    b.HasIndex("DepartmentIdAtSubmission")
                        .HasDatabaseName("ix_budget_requests_department_id_at_submission");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_budget_requests_requester_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_budget_requests_status");

                    b.HasIndex("WithdrawMethodId")
                        .HasDatabaseName("ix_budget_requests_withdraw_method_id");

                    b.HasIndex("DepartmentIdAtSubmission", "Status", "SubmittedAt")
                        .HasDatabaseName("ix_budget_requests_department_id_at_submission_status_submitte");

                    b.ToTable("budget_requests", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.BudgetRequestModification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_request_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.HasKey("Id")
                        .HasName("pk_budget_request_modifications");

                    b.HasIndex("BudgetRequestId")
                        .HasDatabaseName("ix_budget_request_modifications_budget_request_id");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("ix_budget_request_modifications_modified_at");

                    b.HasIndex("ModifiedByUserId")
                        .HasDatabaseName("ix_budget_request_modifications_modified_by_user_id");

                    b.ToTable("budget_request_modifications", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Coa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_coas");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_coas_code");

                    b.ToTable("coas", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("RateToMmk")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rate_to_mmk");

                    b.Property<DateTime>("RateUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rate_updated_at");

                    b.HasKey("Code")
                        .HasName("ak_currencies_code");

                    b.ToTable("currencies", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.CurrencyRateChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("NewRate")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("new_rate");

                    b.Property<decimal>("OldRate")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("old_rate");

                    b.HasKey("Id")
                        .HasName("pk_currency_rate_changes");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("ix_currency_rate_changes_changed_at");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_currency_rate_changes_currency_code");

                    b.ToTable("currency_rate_changes", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BudgetLimit")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("budget_limit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("HeadUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("head_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MonthlyLimit")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SlackWebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("slack_webhook_url");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_name");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<Guid>("BudgetRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_request_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("BudgetRequestId")
                        .HasDatabaseName("ix_payments_budget_request_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFinanceApprover")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finance_approver");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("SlackUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slack_user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_users_department_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.WithdrawMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresAttachment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_attachment");

                    b.HasKey("Id")
                        .HasName("pk_withdraw_methods");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_withdraw_methods_name");

                    b.ToTable("withdraw_methods", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Infrastructure.Notifications.NotificationOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_notification_outbox");

                    b.HasIndex("IsProcessed")
                        .HasDatabaseName("ix_notification_outbox_is_processed");

                    b.ToTable("notification_outbox", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.AdvanceUsage", b =>
                {
                    b.HasOne("SureBudgetRequest.Domain.Entities.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_advance_usages_attachments_attachment_id");

                    b.HasOne("SureBudgetRequest.Domain.Entities.BudgetRequest", null)
                        .WithMany("AdvanceUsages")
                        .HasForeignKey("BudgetRequestId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_advance_usages_budget_requests_budget_request_id");
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.ApprovalAction", b =>
                {
                    b.HasOne("SureBudgetRequest.Domain.Entities.BudgetRequest", null)
                        .WithMany("ApprovalActions")
                        .HasForeignKey("BudgetRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_actions_budget_requests_budget_request_id");
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("SureBudgetRequest.Domain.Entities.BudgetRequest", null)
                        .WithMany("Attachments")
                        .HasForeignKey("BudgetRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_budget_requests_budget_request_id");
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.BudgetRequest", b =>
                {
                    b.HasOne("SureBudgetRequest.Domain.Entities.BudgetCategory", null)
                        .WithMany()
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_budget_requests_budget_categories_budget_category_id");

                    b.HasOne("SureBudgetRequest.Domain.Entities.Coa", null)
                        .WithMany()
                        .HasForeignKey("CoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_budget_requests_coas_coa_id");

                    b.HasOne("SureBudgetRequest.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_budget_requests_currencies_currency_code");

                    b.HasOne("SureBudgetRequest.Domain.Entities.WithdrawMethod", null)
                        .WithMany()
                        .HasForeignKey("WithdrawMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_budget_requests_withdraw_methods_withdraw_method_id");
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.BudgetRequestModification", b =>
                {
                    b.HasOne("SureBudgetRequest.Domain.Entities.BudgetRequest", null)
                        .WithMany()
                        .HasForeignKey("BudgetRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_budget_request_modifications_budget_requests_budget_request");

                    b.HasOne("SureBudgetRequest.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_budget_request_modifications_users_modified_by_user_id");
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.CurrencyRateChange", b =>
                {
                    b.HasOne("SureBudgetRequest.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_currency_rate_changes_currencies_currency_code");
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SureBudgetRequest.Domain.Entities.BudgetRequest", null)
                        .WithMany("Payments")
                        .HasForeignKey("BudgetRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_budget_requests_budget_request_id");
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.BudgetRequest", b =>
                {
                    b.Navigation("AdvanceUsages");

                    b.Navigation("ApprovalActions");

                    b.Navigation("Attachments");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
