// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SureBudgetRequest.Infrastructure.Persistence;

#nullable disable

namespace SureBudgetRequest.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511082747_changeHeadisNullableForDepartment")]
    partial class changeHeadisNullableForDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.ApprovalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actioned_at");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_id");

                    b.Property<Guid>("BudgetRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_request_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.HasKey("Id")
                        .HasName("pk_approval_actions");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("ix_approval_actions_approver_id");

                    b.HasIndex("BudgetRequestId")
                        .HasDatabaseName("ix_approval_actions_budget_request_id");

                    b.ToTable("approval_actions", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BudgetRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_request_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("stored_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("BudgetRequestId")
                        .HasDatabaseName("ix_attachments_budget_request_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.BudgetRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsPartialPayment")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_partial_payment");

                    b.Property<decimal>("ApprovedAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("approved_amount");

                    b.Property<Guid?>("BossIdAtSubmission")
                        .HasColumnType("uuid")
                        .HasColumnName("boss_id_at_submission");

                    b.Property<string>("BossNameAtSubmission")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("boss_name_at_submission");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentIdAtSubmission")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id_at_submission");

                    b.Property<decimal>("DepartmentLimitAtSubmission")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("department_limit_at_submission");

                    b.Property<Guid>("DeptHeadIdAtSubmission")
                        .HasColumnType("uuid")
                        .HasColumnName("dept_head_id_at_submission");

                    b.Property<string>("DeptHeadNameAtSubmission")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dept_head_name_at_submission");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<string>("PartialPaymentDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("partial_payment_detail");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reasons");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_date");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("requested_amount");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("RequesterNameAtSubmission")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requester_name_at_submission");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("WithdrawerJobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("withdrawer_job_title");

                    b.Property<string>("WithdrawerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("withdrawer_name");

                    b.HasKey("Id")
                        .HasName("pk_budget_requests");

                    b.HasIndex("DepartmentIdAtSubmission")
                        .HasDatabaseName("ix_budget_requests_department_id_at_submission");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_budget_requests_requester_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_budget_requests_status");

                    b.ToTable("budget_requests", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BudgetLimit")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("budget_limit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("HeadUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("head_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_name");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BudgetRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_request_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("BudgetRequestId")
                        .HasDatabaseName("ix_payments_budget_request_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("SlackUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slack_user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_users_department_id");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Infrastructure.Notifications.NotificationOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_notification_outbox");

                    b.HasIndex("IsProcessed")
                        .HasDatabaseName("ix_notification_outbox_is_processed");

                    b.ToTable("notification_outbox", (string)null);
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.ApprovalAction", b =>
                {
                    b.HasOne("SureBudgetRequest.Domain.Entities.BudgetRequest", null)
                        .WithMany("ApprovalActions")
                        .HasForeignKey("BudgetRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_actions_budget_requests_budget_request_id");
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("SureBudgetRequest.Domain.Entities.BudgetRequest", null)
                        .WithMany("Attachments")
                        .HasForeignKey("BudgetRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_budget_requests_budget_request_id");
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SureBudgetRequest.Domain.Entities.BudgetRequest", null)
                        .WithMany("Payments")
                        .HasForeignKey("BudgetRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_budget_requests_budget_request_id");
                });

            modelBuilder.Entity("SureBudgetRequest.Domain.Entities.BudgetRequest", b =>
                {
                    b.Navigation("ApprovalActions");

                    b.Navigation("Attachments");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
